
module.exports = [

/* ======================= BCA ======================= */
{
  title: "Computer Applications Intern",
  skills: ["computer basics", "documentation", "ms office"],
  degree: ["BCA"],
  branch: ["Computer Applications"],
  cgpaMin: 5,
  platform: "Internshala",
  duration: "2 Months",
  stipend: "Unpaid",
  link: "https://internshala.com/internships/computer-application-internship",
  image: "https://images.unsplash.com/photo-1517433456452-f9633a875f6f"
},
{
  title: "Office Automation Intern",
  skills: ["excel", "word", "data entry"],
  degree: ["BCA"],
  branch: ["Computer Applications"],
  cgpaMin: 5,
  platform: "Indeed",
  duration: "1 Month",
  stipend: "₹3,000 / month",
  link: "https://in.indeed.com/",
  image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d"
},
{
  title: "Database Support Intern",
  skills: ["sql", "dbms"],
  degree: ["BCA"],
  branch: ["Computer Applications"],
  cgpaMin: 6,
  platform: "Internshala",
  duration: "3 Months",
  stipend: "₹5,000 / month",
  link: "https://internshala.com/",
  image: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d"
},
{
  title: "IT Support Intern",
  skills: ["troubleshooting", "hardware", "software"],
  degree: ["BCA"],
  branch: ["Computer Applications"],
  cgpaMin: 5,
  platform: "LinkedIn",
  duration: "2 Months",
  stipend: "Unpaid",
  link: "https://www.linkedin.com/jobs/",
  image: "https://images.unsplash.com/photo-1581091870627-3fdc1b88a9d5"
},
{
  title: "Junior System Admin Intern",
  skills: ["os", "networking basics"],
  degree: ["BCA"],
  branch: ["Computer Applications"],
  cgpaMin: 6,
  platform: "Indeed",
  duration: "3 Months",
  stipend: "₹6,000 / month",
  link: "https://in.indeed.com/",
  image: "https://images.unsplash.com/photo-1504639725590-34d0984388bd"
},
{
  title: "Web Development Intern",
  skills: ["html", "css", "javascript"],
  degree: ["BCA"],
  branch: ["Software Development"],
  cgpaMin: 6,
  platform: "Internshala",
  duration: "3 Months",
  stipend: "₹8,000 / month",
  link: "https://internshala.com/internships/web-development-internship",
  image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c"
},
{
  title: "Full Stack Developer Intern",
  skills: ["react", "nodejs", "mongodb"],
  degree: ["BCA"],
  branch: ["Software Development"],
  cgpaMin: 7,
  platform: "LinkedIn",
  duration: "6 Months",
  stipend: "₹12,000 / month",
  link: "https://www.linkedin.com/jobs/",
  image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4"
},
{
  title: "Java Developer Intern",
  skills: ["java", "oops"],
  degree: ["BCA"],
  branch: ["Software Development"],
  cgpaMin: 6,
  platform: "Indeed",
  duration: "3 Months",
  stipend: "₹7,000 / month",
  link: "https://in.indeed.com/",
  image: "https://images.unsplash.com/photo-1505685296765-3a2736de412f"
},
{
  title: "Backend Developer Intern",
  skills: ["nodejs", "express"],
  degree: ["BCA"],
  branch: ["Software Development"],
  cgpaMin: 6,
  platform: "Internshala",
  duration: "2 Months",
  stipend: "₹5,000 / month",
  link: "https://internshala.com/",
  image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c"
},
{
  title: "Software Testing Intern",
  skills: ["manual testing", "automation basics"],
  degree: ["BCA"],
  branch: ["Software Development"],
  cgpaMin: 5,
  platform: "Indeed",
  duration: "1 Month",
  stipend: "Unpaid",
  link: "https://in.indeed.com/",
  image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c"
},
{
  title: "Data Analyst Intern",
  skills: ["excel", "sql", "data analysis"],
  degree: ["BCA"],
  branch: ["Data Science"],
  cgpaMin: 6,
  platform: "Internshala",
  duration: "3 Months",
  stipend: "₹10,000 / month",
  link: "https://internshala.com/",
  image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71"
},
{
  title: "Python Data Intern",
  skills: ["python", "pandas"],
  degree: ["BCA"],
  branch: ["Data Science"],
  cgpaMin: 6,
  platform: "Coursera",
  duration: "2 Months",
  stipend: "Unpaid",
  link: "https://www.coursera.org/",
  image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4"
},
{
  title: "Machine Learning Intern",
  skills: ["machine learning", "python"],
  degree: ["BCA"],
  branch: ["Data Science"],
  cgpaMin: 7,
  platform: "LinkedIn",
  duration: "6 Months",
  stipend: "₹15,000 / month",
  link: "https://www.linkedin.com/jobs/",
  image: "https://images.unsplash.com/photo-1504639725590-34d0984388bd"
},
{
  title: "Business Data Intern",
  skills: ["statistics", "data visualization"],
  degree: ["BCA"],
  branch: ["Data Science"],
  cgpaMin: 6,
  platform: "Indeed",
  duration: "2 Months",
  stipend: "₹6,000 / month",
  link: "https://in.indeed.com/",
  image: "https://images.unsplash.com/photo-1526378722484-cc5c5102d6c6"
},
{
  title: "SQL Data Intern",
  skills: ["sql", "databases"],
  degree: ["BCA"],
  branch: ["Data Science"],
  cgpaMin: 5,
  platform: "Internshala",
  duration: "1 Month",
  stipend: "₹4,000 / month",
  link: "https://internshala.com/",
  image: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d"
},


/* ======================= BE  ======================= */
{
  title: "Software Development Intern",
  company: "Infosys",
  skills: ["java", "data structures", "oop"],
  degree: ["BE"],
  branch: ["Computer Science Engineering"],
  cgpaMin: 6,
  duration: "3 Months",
  stipend: "₹10,000 / month",
  link: "https://www.infosys.com/careers/",
  image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4"
},
{
  title: "Web Development Intern",
  company: "TCS",
  skills: ["html", "css", "javascript"],
  degree: ["BE"],
  branch: ["Computer Science Engineering"],
  cgpaMin: 6,
  duration: "2 Months",
  stipend: "₹8,000 / month",
  link: "https://www.tcs.com/careers",
  image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c"
},
{
  title: "AI & ML Intern",
  company: "IBM",
  skills: ["python", "machine learning"],
  degree: ["BE"],
  branch: ["Computer Science Engineering"],
  cgpaMin: 7,
  duration: "6 Months",
  stipend: "₹15,000 / month",
  link: "https://www.ibm.com/careers",
  image: "https://images.unsplash.com/photo-1581092334391-5a4e97d5c9f1"
},
{
  title: "Cloud Computing Intern",
  company: "Amazon AWS",
  skills: ["cloud", "aws"],
  degree: ["BE"],
  branch: ["Computer Science Engineering"],
  cgpaMin: 6,
  duration: "3 Months",
  stipend: "₹12,000 / month",
  link: "https://aws.amazon.com/careers/",
  image: "https://images.unsplash.com/photo-1504639725590-34d0984388bd"
},
{
  title: "Cyber Security Intern",
  company: "Cisco",
  skills: ["network security", "cyber security"],
  degree: ["BE"],
  branch: ["Computer Science Engineering"],
  cgpaMin: 6,
  duration: "4 Months",
  stipend: "₹14,000 / month",
  link: "https://www.cisco.com/careers/",
  image: "https://images.unsplash.com/photo-1510511459019-5dda7724fd87"
},
{
  title: "IT Support Intern",
  company: "Wipro",
  skills: ["networking", "troubleshooting"],
  degree: ["BE"],
  branch: ["Information Technology"],
  cgpaMin: 5,
  duration: "2 Months",
  stipend: "₹6,000 / month",
  link: "https://careers.wipro.com/",
  image: "https://images.unsplash.com/photo-1581090700227-1e37b190418e"
},
{
  title: "Web Technologies Intern",
  company: "Zoho",
  skills: ["html", "css", "javascript"],
  degree: ["BE"],
  branch: ["Information Technology"],
  cgpaMin: 6,
  duration: "3 Months",
  stipend: "₹9,000 / month",
  link: "https://www.zoho.com/careers/",
  image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c"
},
{
  title: "Cloud Operations Intern",
  company: "Google",
  skills: ["cloud", "linux"],
  degree: ["BE"],
  branch: ["Information Technology"],
  cgpaMin: 7,
  duration: "6 Months",
  stipend: "₹20,000 / month",
  link: "https://careers.google.com/",
  image: "https://images.unsplash.com/photo-1504639725590-34d0984388bd"
},
{
  title: "Data Analytics Intern",
  company: "Accenture",
  skills: ["data analysis", "excel"],
  degree: ["BE"],
  branch: ["Information Technology"],
  cgpaMin: 6,
  duration: "3 Months",
  stipend: "₹10,000 / month",
  link: "https://www.accenture.com/careers",
  image: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d"
},
{
  title: "Cyber Security Operations Intern",
  company: "HCL",
  skills: ["cyber security", "network monitoring"],
  degree: ["BE"],
  branch: ["Information Technology"],
  cgpaMin: 6,
  duration: "4 Months",
  stipend: "₹12,000 / month",
  link: "https://www.hcltech.com/careers",
  image: "https://images.unsplash.com/photo-1510511459019-5dda7724fd87"
},
{
  title: "Mechanical Design Intern",
  company: "L&T",
  skills: ["autocad", "solidworks"],
  degree: ["BE"],
  branch: ["Mechanical Engineering"],
  cgpaMin: 6,
  duration: "3 Months",
  stipend: "₹8,000 / month",
  link: "https://www.larsentoubro.com/careers/",
  image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789"
},
{
  title: "Production Engineering Intern",
  company: "Tata Motors",
  skills: ["manufacturing", "quality control"],
  degree: ["BE"],
  branch: ["Mechanical Engineering"],
  cgpaMin: 6,
  duration: "6 Months",
  stipend: "₹12,000 / month",
  link: "https://www.tatamotors.com/careers/",
  image: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc"
},
{
  title: "Maintenance Engineering Intern",
  company: "BHEL",
  skills: ["maintenance", "power plant"],
  degree: ["BE"],
  branch: ["Mechanical Engineering"],
  cgpaMin: 5,
  duration: "3 Months",
  stipend: "₹7,000 / month",
  link: "https://www.bhel.com/careers",
  image: "https://images.unsplash.com/photo-1504639725590-34d0984388bd"
},
{
  title: "Thermal Systems Intern",
  company: "NTPC",
  skills: ["thermodynamics", "energy systems"],
  degree: ["BE"],
  branch: ["Mechanical Engineering"],
  cgpaMin: 6,
  duration: "2 Months",
  stipend: "₹6,000 / month",
  link: "https://www.ntpc.co.in/careers",
  image: "https://images.unsplash.com/photo-1509395176047-4a66953fd231"
},
{
  title: "Robotics & Automation Intern",
  company: "Bosch",
  skills: ["robotics", "automation"],
  degree: ["BE"],
  branch: ["Mechanical Engineering"],
  cgpaMin: 7,
  duration: "6 Months",
  stipend: "₹15,000 / month",
  link: "https://www.bosch.in/careers/",
  image: "https://images.unsplash.com/photo-1504639725590-34d0984388bd"
},
{
  title: "Site Engineering Intern",
  company: "L&T Construction",
  skills: ["site management", "construction"],
  degree: ["BE"],
  branch: ["Civil Engineering"],
  cgpaMin: 5,
  duration: "3 Months",
  stipend: "₹6,000 / month",
  link: "https://www.larsentoubro.com/careers/",
  image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e"
},
{
  title: "Structural Design Intern",
  company: "AECOM",
  skills: ["structural analysis", "design"],
  degree: ["BE"],
  branch: ["Civil Engineering"],
  cgpaMin: 6,
  duration: "6 Months",
  stipend: "₹15,000 / month",
  link: "https://aecom.com/careers/",
  image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5"
},
{
  title: "Highway Engineering Intern",
  company: "NHAI",
  skills: ["highway design", "surveying"],
  degree: ["BE"],
  branch: ["Civil Engineering"],
  cgpaMin: 6,
  duration: "2 Months",
  stipend: "₹5,000 / month",
  link: "https://nhai.gov.in/",
  image: "https://images.unsplash.com/photo-1504306669229-14d0d7c0c7c5"
},
{
  title: "Environmental Engineering Intern",
  company: "Tata Projects",
  skills: ["water treatment", "environment"],
  degree: ["BE"],
  branch: ["Civil Engineering"],
  cgpaMin: 5,
  duration: "3 Months",
  stipend: "₹7,000 / month",
  link: "https://www.tataprojects.com/careers/",
  image: "https://images.unsplash.com/photo-1509395176047-4a66953fd231"
},
{
  title: "Quantity Surveying Intern",
  company: "Shapoorji Pallonji",
  skills: ["estimation", "costing"],
  degree: ["BE"],
  branch: ["Civil Engineering"],
  cgpaMin: 6,
  duration: "4 Months",
  stipend: "₹8,000 / month",
  link: "https://www.shapoorjipallonji.com/careers/",
  image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e"
},


/* ======================= BBA ======================= */
{
  title: "Finance Analyst Internship",
  skills: ["financial analysis", "excel", "accounting"],
  degree: ["BBA"],
  branch: ["Finance"],
  cgpaMin: 5,
  platform: "Internshala",
  link: "https://internshala.com/internships/finance-internship",
  image: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c"
},
{
  title: "Investment Banking Intern",
  skills: ["investment banking", "valuation"],
  degree: ["BBA"],
  branch: ["Finance"],
  cgpaMin: 6,
  platform: "LinkedIn",
  link: "https://www.linkedin.com/jobs",
  image: "https://images.unsplash.com/photo-1565373677928-90e963765eac"
},
{
  title: "Corporate Finance Internship",
  skills: ["corporate finance", "budgeting"],
  degree: ["BBA"],
  branch: ["Finance"],
  cgpaMin: 5,
  platform: "Indeed",
  link: "https://in.indeed.com",
  image: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a"
},
{
  title: "Accounts & Taxation Intern",
  skills: ["accounting", "taxation", "tally"],
  degree: ["BBA"],
  branch: ["Finance"],
  cgpaMin: 4,
  platform: "Internshala",
  link: "https://internshala.com/internships/accounting-internship",
  image: "https://images.unsplash.com/photo-1581091870627-3f9c5fae1b6e"
},
{
  title: "Financial Modeling Internship",
  skills: ["financial modeling", "excel"],
  degree: ["BBA"],
  branch: ["Finance"],
  cgpaMin: 6,
  platform: "AngelList",
  link: "https://angel.co/jobs",
  image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71"
},
{
  title: "Digital Marketing Internship",
  skills: ["digital marketing", "seo", "social media"],
  degree: ["BBA"],
  branch: ["Marketing"],
  cgpaMin: 4,
  platform: "Internshala",
  link: "https://internshala.com/internships/digital-marketing-internship",
  image: "https://images.unsplash.com/photo-1557838923-2985c318be48"
},
{
  title: "Social Media Marketing Intern",
  skills: ["instagram marketing", "content creation"],
  degree: ["BBA"],
  branch: ["Marketing"],
  cgpaMin: 0,
  platform: "LinkedIn",
  link: "https://www.linkedin.com/jobs",
  image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7"
},
{
  title: "Brand Management Internship",
  skills: ["branding", "market research"],
  degree: ["BBA"],
  branch: ["Marketing"],
  cgpaMin: 5,
  platform: "Indeed",
  link: "https://in.indeed.com",
  image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0"
},
{
  title: "Marketing Research Intern",
  skills: ["market research", "data analysis"],
  degree: ["BBA"],
  branch: ["Marketing"],
  cgpaMin: 5,
  platform: "Internshala",
  link: "https://internshala.com/internships/marketing-internship",
  image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f"
},
{
  title: "Performance Marketing Intern",
  skills: ["google ads", "facebook ads"],
  degree: ["BBA"],
  branch: ["Marketing"],
  cgpaMin: 6,
  platform: "AngelList",
  link: "https://angel.co/jobs",
  image: "https://images.unsplash.com/photo-1553877522-43269d4ea984"
},
{
  title: "Human Resources Internship",
  skills: ["recruitment", "hr operations"],
  degree: ["BBA"],
  branch: ["HR"],
  cgpaMin: 4,
  platform: "Internshala",
  link: "https://internshala.com/internships/hr-internship",
  image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d"
},
{
  title: "Talent Acquisition Intern",
  skills: ["hiring", "interviewing"],
  degree: ["BBA"],
  branch: ["HR"],
  cgpaMin: 5,
  platform: "LinkedIn",
  link: "https://www.linkedin.com/jobs",
  image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c"
},
{
  title: "HR Operations Intern",
  skills: ["employee engagement", "documentation"],
  degree: ["BBA"],
  branch: ["HR"],
  cgpaMin: 4,
  platform: "Indeed",
  link: "https://in.indeed.com",
  image: "https://images.unsplash.com/photo-1552664730-d307ca884978"
},
{
  title: "Payroll & Compliance Intern",
  skills: ["payroll", "labor laws"],
  degree: ["BBA"],
  branch: ["HR"],
  cgpaMin: 6,
  platform: "Internshala",
  link: "https://internshala.com/internships/hr-internship",
  image: "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70"
},
{
  title: "HR Analytics Intern",
  skills: ["hr analytics", "excel"],
  degree: ["BBA"],
  branch: ["HR"],
  cgpaMin: 6,
  platform: "AngelList",
  link: "https://angel.co/jobs",
  image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71"
},


/* ======================= BCOM ======================= */
{
  title: "Business Operations Intern",
  skills: ["business operations", "reporting", "communication"],
  degree: ["BCOM"],
  branch: ["General Commerce"],
  cgpaMin: 5,
  platform: "Internshala",
  link: "https://internshala.com/internships/business-internship",
  image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f"
},
{
  title: "Sales & Commerce Intern",
  skills: ["sales", "customer handling", "market analysis"],
  degree: ["BCOM"],
  branch: ["General Commerce"],
  cgpaMin: 5,
  platform: "Indeed",
  link: "https://in.indeed.com/q-sales-intern-jobs.html",
  image: "https://images.unsplash.com/photo-1549924231-f129b911e442"
},
{
  title: "Business Research Intern",
  skills: ["research", "data collection", "analysis"],
  degree: ["BCOM"],
  branch: ["General Commerce"],
  cgpaMin: 6,
  platform: "LinkedIn",
  link: "https://www.linkedin.com/jobs/business-research-intern-jobs/",
  image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df"
},
{
  title: "Supply Chain Intern",
  skills: ["logistics", "inventory", "coordination"],
  degree: ["BCOM"],
  branch: ["General Commerce"],
  cgpaMin: 5,
  platform: "Internshala",
  link: "https://internshala.com/internships/supply-chain-internship",
  image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d"
},
{
  title: "Operations Management Intern",
  skills: ["operations", "process improvement", "documentation"],
  degree: ["BCOM"],
  branch: ["General Commerce"],
  cgpaMin: 6,
  platform: "Indeed",
  link: "https://in.indeed.com/q-operations-intern-jobs.html",
  image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e"
},
{
  title: "Accounting Intern",
  skills: ["accounting", "bookkeeping", "ledger entries"],
  degree: ["BCOM"],
  branch: ["Accounting"],
  cgpaMin: 6,
  platform: "Internshala",
  link: "https://internshala.com/internships/accounting-internship",
  image: "https://images.unsplash.com/photo-1554224154-22dec7ec8818"
},
{
  title: "Finance & Accounts Intern",
  skills: ["financial reporting", "accounting", "excel"],
  degree: ["BCOM"],
  branch: ["Accounting"],
  cgpaMin: 6,
  platform: "Indeed",
  link: "https://in.indeed.com/q-finance-accounting-intern-jobs.html",
  image: "https://images.unsplash.com/photo-1556761175-4b46a572b786"
},
{
  title: "GST & Taxation Intern",
  skills: ["gst", "tax filing", "compliance"],
  degree: ["BCOM"],
  branch: ["Accounting"],
  cgpaMin: 5,
  platform: "Internshala",
  link: "https://internshala.com/internships/taxation-internship",
  image: "https://images.unsplash.com/photo-1586486855514-8c633cc6fd38"
},
{
  title: "Audit Intern",
  skills: ["auditing", "financial analysis", "documentation"],
  degree: ["BCOM"],
  branch: ["Accounting"],
  cgpaMin: 6,
  platform: "LinkedIn",
  link: "https://www.linkedin.com/jobs/audit-intern-jobs/",
  image: "https://images.unsplash.com/photo-1518546305927-5a555bb7020d"
},
{
  title: "Tally ERP Intern",
  skills: ["tally", "accounting software", "gst"],
  degree: ["BCOM"],
  branch: ["Accounting"],
  cgpaMin: 5,
  platform: "Udemy",
  link: "https://www.udemy.com/topic/tally/",
  image: "https://images.unsplash.com/photo-1605902711622-cfb43c4437d1"
},


/* ======================= BSC ======================= */
{
  title: "Software Development Intern",
  company: "TechNova Solutions",
  skills: ["python", "java", "problem solving"],
  degree: ["BSC"],
  branch: ["Computer Science"],
  duration: "3 Months",
  stipend: "₹8,000/month",
  cgpaMin: 6,
  link: "https://internshala.com/software-development-internship",
  image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c"
},
{
  title: "Web Development Intern",
  company: "WebWorks India",
  skills: ["html", "css", "javascript"],
  degree: ["BSC"],
  branch: ["Computer Science"],
  duration: "2 Months",
  stipend: "₹6,000/month",
  cgpaMin: 5,
  link: "https://internshala.com/web-development-internship",
  image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085"
},
{
  title: "Data Science Intern",
  company: "DataMinds",
  skills: ["python", "statistics", "machine learning"],
  degree: ["BSC"],
  branch: ["Computer Science"],
  duration: "4 Months",
  stipend: "₹10,000/month",
  cgpaMin: 7,
  link: "https://internshala.com/data-science-internship",
  image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71"
},
{
  title: "Cyber Security Intern",
  company: "SecureNet",
  skills: ["networking", "cyber security", "linux"],
  degree: ["BSC"],
  branch: ["Computer Science"],
  duration: "3 Months",
  stipend: "₹9,000/month",
  cgpaMin: 6,
  link: "https://internshala.com/cyber-security-internship",
  image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b"
},
{
  title: "Database Management Intern",
  company: "InfoSys Data Labs",
  skills: ["sql", "dbms", "data handling"],
  degree: ["BSC"],
  branch: ["Computer Science"],
  duration: "2 Months",
  stipend: "₹7,000/month",
  cgpaMin: 5,
  link: "https://internshala.com/database-internship",
  image: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d"
},
{
  title: "Data Analyst Intern",
  company: "Insight Analytics",
  skills: ["statistics", "excel", "python"],
  degree: ["BSC"],
  branch: ["Mathematics"],
  duration: "3 Months",
  stipend: "₹8,000/month",
  cgpaMin: 6,
  link: "https://internshala.com/data-analyst-internship",
  image: "https://images.unsplash.com/photo-1526378722443-4bdaecfa2f77"
},
{
  title: "Operations Research Intern",
  company: "OptiSolve",
  skills: ["optimization", "linear programming"],
  degree: ["BSC"],
  branch: ["Mathematics"],
  duration: "2 Months",
  stipend: "₹6,000/month",
  cgpaMin: 6,
  link: "https://internshala.com/operations-research-internship",
  image: "https://images.unsplash.com/photo-1509228468518-180dd4864904"
},
{
  title: "Business Analytics Intern",
  company: "BizMetrics",
  skills: ["statistics", "data analysis", "excel"],
  degree: ["BSC"],
  branch: ["Mathematics"],
  duration: "3 Months",
  stipend: "₹7,000/month",
  cgpaMin: 5,
  link: "https://internshala.com/business-analytics-internship",
  image: "https://images.unsplash.com/photo-1532619675605-1ede6c2ed2b0"
},
{
  title: "Research Assistant Intern",
  company: "Math Research Lab",
  skills: ["mathematical modeling", "research"],
  degree: ["BSC"],
  branch: ["Mathematics"],
  duration: "4 Months",
  stipend: "₹9,000/month",
  cgpaMin: 7,
  link: "https://internshala.com/research-internship",
  image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb"
},
{
  title: "Quantitative Analysis Intern",
  company: "FinQuant",
  skills: ["probability", "statistics", "analysis"],
  degree: ["BSC"],
  branch: ["Mathematics"],
  duration: "3 Months",
  stipend: "₹10,000/month",
  cgpaMin: 7,
  link: "https://internshala.com/quantitative-analyst-internship",
  image: "https://images.unsplash.com/photo-1518779578993-ec3579fee39f"
},
{
  title: "Physics Research Intern",
  company: "National Research Lab",
  skills: ["research", "data analysis", "physics concepts"],
  degree: ["BSC"],
  branch: ["Physics"],
  duration: "4 Months",
  stipend: "₹8,000/month",
  cgpaMin: 6,
  link: "https://internshala.com/physics-research-internship",
  image: "https://images.unsplash.com/photo-1507413245164-6160d8298b31"
},
{
  title: "Astrophysics Intern",
  company: "Space Science Center",
  skills: ["astrophysics", "data modeling"],
  degree: ["BSC"],
  branch: ["Physics"],
  duration: "3 Months",
  stipend: "₹10,000/month",
  cgpaMin: 7,
  link: "https://internshala.com/astrophysics-internship",
  image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa"
},
{
  title: "Electronics & Instrumentation Intern",
  company: "ElectroLabs",
  skills: ["electronics", "instrumentation"],
  degree: ["BSC"],
  branch: ["Physics"],
  duration: "2 Months",
  stipend: "₹6,000/month",
  cgpaMin: 5,
  link: "https://internshala.com/electronics-internship",
  image: "https://images.unsplash.com/photo-1518770660439-4636190af475"
},
{
  title: "Computational Physics Intern",
  company: "SimuTech",
  skills: ["python", "simulation", "numerical methods"],
  degree: ["BSC"],
  branch: ["Physics"],
  duration: "3 Months",
  stipend: "₹9,000/month",
  cgpaMin: 6,
  link: "https://internshala.com/computational-physics-internship",
  image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee"
},
{
  title: "Laboratory Assistant Intern",
  company: "Advanced Physics Lab",
  skills: ["experiments", "data recording"],
  degree: ["BSC"],
  branch: ["Physics"],
  duration: "2 Months",
  stipend: "₹5,000/month",
  cgpaMin: 5,
  link: "https://internshala.com/lab-assistant-internship",
  image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d"
},


/* ======================= BED ======================= */
{
  title: "English Teaching Intern",
  company: "ABC International School",
  skills: ["communication", "lesson planning", "grammar"],
  degree: ["BED"],
  branch: ["English"],
  cgpaMin: 5,
  duration: "3 Months",
  stipend: "₹5,000/month",
  link: "https://internshala.com/english-teaching-internship",
  image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f"
},
{
  title: "Content Writing & Teaching Intern",
  company: "EduLearn Academy",
  skills: ["creative writing", "content development"],
  degree: ["BED"],
  branch: ["English"],
  cgpaMin: 5,
  duration: "2 Months",
  stipend: "₹4,000/month",
  link: "https://internshala.com/content-writing-internship",
  image: "https://images.unsplash.com/photo-1455390582262-044cdead277a"
},
{
  title: "Online English Tutor Intern",
  company: "Vedantu",
  skills: ["online teaching", "communication"],
  degree: ["BED"],
  branch: ["English"],
  cgpaMin: 6,
  duration: "3 Months",
  stipend: "₹6,000/month",
  link: "https://www.vedantu.com/careers",
  image: "https://images.unsplash.com/photo-1519681393784-d120267933ba"
},
{
  title: "Spoken English Trainer Intern",
  company: "British Council Partner",
  skills: ["spoken english", "presentation"],
  degree: ["BED"],
  branch: ["English"],
  cgpaMin: 6,
  duration: "2 Months",
  stipend: "₹7,000/month",
  link: "https://internshala.com/spoken-english-internship",
  image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f"
},
{
  title: "English Curriculum Developer Intern",
  company: "EdTech Solutions",
  skills: ["curriculum design", "lesson planning"],
  degree: ["BED"],
  branch: ["English"],
  cgpaMin: 6,
  duration: "3 Months",
  stipend: "₹8,000/month",
  link: "https://internshala.com/curriculum-development-internship",
  image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3"
},
{
  title: "Science Teaching Intern",
  company: "Green Valley School",
  skills: ["lesson planning", "scientific thinking"],
  degree: ["BED"],
  branch: ["Science"],
  cgpaMin: 5,
  duration: "3 Months",
  stipend: "₹5,000/month",
  link: "https://internshala.com/science-teaching-internship",
  image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d"
},
{
  title: "STEM Education Intern",
  company: "STEM India",
  skills: ["stem", "problem solving"],
  degree: ["BED"],
  branch: ["Science"],
  cgpaMin: 6,
  duration: "2 Months",
  stipend: "₹6,000/month",
  link: "https://internshala.com/stem-internship",
  image: "https://images.unsplash.com/photo-1581091012184-7c54ab2f7b83"
},
{
  title: "Virtual Lab Assistant Intern",
  company: "Virtual Labs IIT",
  skills: ["virtual labs", "experiments"],
  degree: ["BED"],
  branch: ["Science"],
  cgpaMin: 5,
  duration: "3 Months",
  stipend: "₹4,000/month",
  link: "https://www.vlab.co.in/",
  image: "https://images.unsplash.com/photo-1526378722443-4bdaecfa2f77"
},
{
  title: "Science Content Developer Intern",
  company: "Byju's",
  skills: ["content creation", "science concepts"],
  degree: ["BED"],
  branch: ["Science"],
  cgpaMin: 6,
  duration: "2 Months",
  stipend: "₹8,000/month",
  link: "https://byjus.com/careers/",
  image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644"
},
{
  title: "Laboratory Management Intern",
  company: "EduLabs",
  skills: ["lab safety", "equipment handling"],
  degree: ["BED"],
  branch: ["Science"],
  cgpaMin: 5,
  duration: "3 Months",
  stipend: "₹5,500/month",
  link: "https://internshala.com/lab-internship",
  image: "https://images.unsplash.com/photo-1507413245164-6160d8298b31"
},
{
  title: "Special Education Teaching Intern",
  company: "Hope Special School",
  skills: ["inclusive education", "student support"],
  degree: ["BED"],
  branch: ["Special Education"],
  cgpaMin: 5,
  duration: "3 Months",
  stipend: "₹6,000/month",
  link: "https://internshala.com/special-education-internship",
  image: "https://images.unsplash.com/photo-1509062522246-3755977927d7"
},
{
  title: "Inclusive Classroom Assistant Intern",
  company: "Inclusive India Foundation",
  skills: ["classroom management", "inclusion"],
  degree: ["BED"],
  branch: ["Special Education"],
  cgpaMin: 6,
  duration: "2 Months",
  stipend: "₹5,000/month",
  link: "https://internshala.com/inclusive-education-internship",
  image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f"
},
{
  title: "Learning Disability Support Intern",
  company: "MindBridge Center",
  skills: ["assessment", "learning support"],
  degree: ["BED"],
  branch: ["Special Education"],
  cgpaMin: 5,
  duration: "3 Months",
  stipend: "₹7,000/month",
  link: "https://internshala.com/learning-disability-internship",
  image: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2"
},
{
  title: "Behavior Therapy Assistant Intern",
  company: "ChildCare Clinic",
  skills: ["behavior analysis", "counseling"],
  degree: ["BED"],
  branch: ["Special Education"],
  cgpaMin: 6,
  duration: "2 Months",
  stipend: "₹8,000/month",
  link: "https://internshala.com/behavior-therapy-internship",
  image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b"
},
{
  title: "Assistive Technology Intern",
  company: "Enable India",
  skills: ["assistive tools", "technology integration"],
  degree: ["BED"],
  branch: ["Special Education"],
  cgpaMin: 6,
  duration: "3 Months",
  stipend: "₹9,000/month",
  link: "https://enableindia.org/careers/",
  image: "https://images.unsplash.com/photo-1584697964192-0b3b9c2c8c4f"
}
];

